# -*- coding: utf-8 -*-
"""DIPLOM_UNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTMs7w9grPQUz_ajFmyFa1l-wFnYdvoi
"""


import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import Sequence
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import load_model, Model
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


base_model = VGG16(weights='imagenet', include_top=False, input_shape=(256, 256, 3))


for layer in base_model.layers:
    layer.trainable = False


c1 = base_model.get_layer('block1_conv2').output
c2 = base_model.get_layer('block2_conv2').output
c3 = base_model.get_layer('block3_conv3').output
c4 = base_model.get_layer('block4_conv3').output
c5 = base_model.get_layer('block5_conv3').output


u6 = layers.Conv2DTranspose(512, (3, 3), strides=(2, 2), padding='same')(c5)
u6 = layers.concatenate([u6, c4])
c6 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(u6)
c6 = layers.Conv2D(512, (3, 3), activation='relu', padding='same')(c6)

u7 = layers.Conv2DTranspose(256, (3, 3), strides=(2, 2), padding='same')(c6)
u7 = layers.concatenate([u7, c3])
c7 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(u7)
c7 = layers.Conv2D(256, (3, 3), activation='relu', padding='same')(c7)

u8 = layers.Conv2DTranspose(128, (3, 3), strides=(2, 2), padding='same')(c7)
u8 = layers.concatenate([u8, c2])
c8 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(u8)
c8 = layers.Conv2D(128, (3, 3), activation='relu', padding='same')(c8)

u9 = layers.Conv2DTranspose(64, (3, 3), strides=(2, 2), padding='same')(c8)
u9 = layers.concatenate([u9, c1])
c9 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(u9)
c9 = layers.Conv2D(64, (3, 3), activation='relu', padding='same')(c9)

outputs = layers.Conv2D(1, (1, 1), activation='sigmoid')(c9)

final_model = Model(inputs=base_model.input, outputs=outputs)

final_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

IMAGE_SIZE = (256, 256)
SIZE_X, SIZE_Y = IMAGE_SIZE

train_dir = '/content/drive/MyDrive/unet_dataset/train'
test_dir = '/content/drive/MyDrive/unet_dataset/test'

def get_image_paths(dir_path, image_type='input'):
    """
    Возвращает список путей к файлам изображений из директории.
    """
    return sorted(
        [os.path.join(dir_path, image_type, fname) for fname in os.listdir(os.path.join(dir_path, image_type)) if fname.endswith('.png')]
    )

def load_data(input_paths, mask_paths, image_size=(256, 256)):
    """Загружает изображения и маски, приводит их к нужному размеру."""
    images = []
    masks = []

    for input_path, mask_path in zip(input_paths, mask_paths):
        img = load_img(input_path, target_size=image_size)
        img = img_to_array(img) / 255.0
        images.append(img)

        mask = load_img(mask_path, target_size=image_size, color_mode='grayscale')
        mask = img_to_array(mask) / 255.0 
        masks.append(mask)

    return np.array(images), np.array(masks)

train_input_paths = get_image_paths(train_dir, 'input')
train_mask_paths = get_image_paths(train_dir, 'mask')
test_input_paths = get_image_paths(test_dir, 'input')
test_mask_paths = get_image_paths(test_dir, 'mask')

train_images, train_masks = load_data(train_input_paths, train_mask_paths)
test_images, test_masks = load_data(test_input_paths, test_mask_paths)

print(f"Train images shape: {train_images.shape}")
print(f"Train masks shape: {train_masks.shape}")
print(f"Test images shape: {test_images.shape}")
print(f"Test masks shape: {test_masks.shape}")

train_images, val_images, train_masks, val_masks = train_test_split(
    train_images, train_masks, test_size=0.2, random_state=42
)

train_images = np.array(train_images) 
train_masks = np.array(train_masks)
val_images = np.array(val_images)
val_masks = np.array(val_masks)

train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_masks))
val_dataset = tf.data.Dataset.from_tensor_slices((val_images, val_masks))

train_dataset = train_dataset.shuffle(100).batch(24)
val_dataset = val_dataset.batch(8)

history = final_model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=50,
    verbose=1
)

final_model.save('unet_model_may.h5')
