# -*- coding: utf-8 -*-
"""DIPLOM_YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whVT8Wt3ySMCYQs5m1oyJo1_04mXmjtb
"""

import ultralytics
from ultralytics import YOLO
import os
import cv2
import time
import torch
import random
import shutil

EPOCHS = 150
NUM_TRAIN_LOOPS = 1
IMG_SIZE = 720
LAYER_FREEZE = 0 

HSV_H = 0.3
HSV_S = 0.7 
HSV_V = 0.4
DEGREES = 0.15
TRANSLATE = 0.3
SCALE = 0.4
SHEAR = 0.01
FLIPUD = 0.3
FLIPLR = 0.3
ERASING = 0.2
CROP_FRACTION = 0.3

DATASETS_DIR = 'drive/MyDrive/dataset/'
DATA_YAML = 'data.yaml'

TRAIN_PERCENTAGE = 1.0

KEEP_EMPTY_FRAMES = True
PERCENTAGE_EMPTY_FRAMES_TO_KEEP = 1.0

RESUME_TRAINING = True

MODEL = 'yolo11s.pt'

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

ONNX_BATCH_SIZE = 4

DATE = time.strftime('%Y-%m-%d-%H-%M-%S')

print("CUDA Available: " + str(torch.cuda.is_available()))
print("Torch CUDA Version: " + str(torch.version.cuda))

ultralytics.utils.checks.collect_system_info()

def train_model(model : YOLO) -> None:
    start_time = time.time()
    model_name = f'{MODEL}-img_size_{IMG_SIZE}_layers_frozen_{LAYER_FREEZE}_{DATE}'
    model.train(
        batch=18,
        data=curr_data_yaml,
        imgsz=IMG_SIZE,
        epochs=EPOCHS,
        freeze=LAYER_FREEZE,
        amp=True,
        cache="disk",
        save=True,
        save_period=10,
        name=model_name,
        hsv_h=HSV_H,
        hsv_s=HSV_S,
        hsv_v=HSV_V,
        degrees=DEGREES,
        translate=TRANSLATE,
        scale=SCALE,
        shear=SHEAR,
        flipud=FLIPUD,
        fliplr=FLIPLR,
        erasing=ERASING,
        crop_fraction=CROP_FRACTION
    )

    end_time = time.time()
    training_time = end_time - start_time
    print("Time to train: ", training_time)

curr_data_yaml = 'data.yaml'

import os
import random
import shutil

def split_dataset(base_dir, train_ratio=0.8, seed=42):
    """
    Разбивает изображения и метки из папок `images` и `labels` в `base_dir`
    на train/val с указанным соотношением.

    :param base_dir: Путь к директории, содержащей папки 'images' и 'labels'
    :param train_ratio: Доля тренировочной выборки (остальное — валидация)
    :param seed: Значение для воспроизводимости случайной выборки
    """
    images_dir = os.path.join(base_dir, 'images')
    labels_dir = os.path.join(base_dir, 'labels')

    image_files = sorted([
        f for f in os.listdir(images_dir)
        if os.path.isfile(os.path.join(images_dir, f))
    ])

    random.seed(seed)
    random.shuffle(image_files)

    split_idx = int(len(image_files) * train_ratio)
    train_files = image_files[:split_idx]
    val_files = image_files[split_idx:]

    def make_dirs(subset):
        os.makedirs(os.path.join(base_dir, subset, 'images'), exist_ok=True)
        os.makedirs(os.path.join(base_dir, subset, 'labels'), exist_ok=True)

    make_dirs('train')
    make_dirs('val')

    def copy_files(files, subset):
        for file in files:
            base_name = os.path.splitext(file)[0]
            image_src = os.path.join(images_dir, file)
            label_src = os.path.join(labels_dir, base_name + '.txt')

            image_dst = os.path.join(base_dir, subset, 'images', file)
            label_dst = os.path.join(base_dir, subset, 'labels', base_name + '.txt')

            shutil.copy(image_src, image_dst)
            if os.path.exists(label_src):
                shutil.copy(label_src, label_dst)
            else:
                print(f"[!] Warning: label file not found for {file}")

    copy_files(train_files, 'train')
    copy_files(val_files, 'val')

    print(f"Разбиение завершено: {len(train_files)} train, {len(val_files)} val")


split_dataset('')

epochs_done = 0
model = YOLO(MODEL)
for _ in range(NUM_TRAIN_LOOPS):
    print(f"Starting training loop starting on epoch {epochs_done}")
    train_model(model)
    epochs_done += EPOCHS
    model_name = f"{MODEL}_{DATE}_batch{ONNX_BATCH_SIZE}_{EPOCHS}epochs"
    model_path = '/content/drive/MyDrive/med_weights' + model_name + '.pt'
    model.save(model_path)


TEST_PATH = 'val/images'

def test_model(model : YOLO, test_results_path: os.PathLike) -> None:
    """
    Test the fine-tuned model on test images and save the results.

    Parameters:
        model (YOLO): The fine-tuned YOLO model.
        test_results_path (os.PathLike): The path to save the test results.

    Returns:
        None

    """
    if not os.path.exists(test_results_path):
        os.makedirs(test_results_path)

    for file in os.listdir(TEST_PATH):
        file_path = os.path.join(TEST_PATH, file)
        output = model.predict(file_path, conf=0.55)
        save_path = os.path.join(test_results_path, file)
        cv2.imwrite(save_path, output[0].plot())

    print("Inference on test set complete. Results saved to: ", test_results_path)

test_model(YOLO('runs/detect/yolo11s.pt-img_size_720_layers_frozen_0_2025-05-26-14-31-09/weights/best.pt'), 'results')
